### ISSUE TITLE
Feed unable to load

### ISSUE THREAD

**Issue by romhacks** [Frontesque/VueTube#243]
- Device:
Pixel 6, Android 13 (DP2)
- VueTube version
Latest (as of 11/4)
- Issue description
The home feed and Search do not load (Home shows loading animation indefinitely) - Search suggestions are visible while typing but actual search is blank.

Screenshots of issue and logs:
![Screenshot_20220411-131452](https://user-images.githubusercontent.com/42524580/162794215-f663e524-1cd0-4c0a-bba4-94e5187b7ace.png)
![Screenshot_20220411-131428](https://user-images.githubusercontent.com/42524580/162794219-b6403878-6666-4053-9aef-6b4457d8ad54.png)

**Comment by 404-Program-not-found** [comment]
Hi there, can you try the latest unstable?

**Comment by romhacks** [comment]
App now throws this toast error and never loads. I suspect it is the same problem. 
![Screenshot_20220411-200918](https://user-images.githubusercontent.com/42524580/162852930-52bb9f9d-3966-4f76-9595-e1bfc9e286b6.png)

**Comment by 404-Program-not-found** [comment]
can you take a screenshot of the first error encountered in the logs?

**Comment by romhacks** [comment]
Quite a lot of HTML. This wasn't present in the older version, but is now.
![StitchIt_20221204090353_963](https://user-images.githubusercontent.com/42524580/162968912-074b3a33-9db6-4a41-ab8b-6268e3925415.png)

**Comment by 404-Program-not-found** [comment]
Thanks for your report. I'll look into the fix.

**Comment by romhacks** [comment]
Just a heads-up - This issue is still present on Android 13 Beta 1 (as well as the now-latest VueTube commit)

**Comment by 404-Program-not-found** [comment]
Unfortunately we cannot support the android 13 beta at the moment due to a problem that is completely out of our control. I would just wait for a full android 13 release.

**Comment by romhacks** [comment]
> Unfortunately we cannot support the android 13 beta at the moment due to a problem that is completely out of our control. I would just wait for a full android 13 release.

Understood. Should I close this issue?

**Comment by 404-Program-not-found** [comment]
I can do that

**Comment by LuanRT** [comment]
@404-Program-not-found maybe this could be fixed by using https://www.youtube.com/sw.js instead of https://www.youtube.com to extract the yt config data? This approach is much faster and the only downside is that the visitor data (used to keep track of recommendations for a session) has to be generated manually, but even that wouldn't be a problem since it's just an 11 character random string + unix timestamp (encoded with protobuf).

See [this](https://github.com/LuanRT/YouTube.js/blob/2315306d9f21dd4e572f58e1c781ec608152518d/lib/core/SessionBuilder.js#L24) and  [this](https://github.com/LuanRT/YouTube.js/blob/2315306d9f21dd4e572f58e1c781ec608152518d/lib/proto/index.js#L14) for more info.

**Comment by 404-Program-not-found** [comment]
I see. Will look into it, thanks!

**Comment by 404-Program-not-found** [comment]
for future reference: the API library has now moved to its own repository: [VueTube-Extractor](https://github.com/vuetubeapp/vuetube-extractor)
