### ISSUE TITLE
Add support for customized startup pages

### ISSUE THREAD

**Issue by Jurtaani** [Frontesque/VueTube#50]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [i open the default YouTube app and it opens up to the "what to watch" page instead of my subscriptions page]

**Describe the solution you'd like**
I would love to be able to select which page do the app open upon startup, one user might like the default "what to watch", and another user might just be interested to open their Playlists page. 
But i most often just want to know what new videos the channels that I'm subscribed to, have uploaded since the last time I looked at them.

**Comment by Svk1190** [comment]
Can we also have an option for a blank page with only the search bar?

Sometimes we plan to search something on youtube, but as soon as we open the app a lot of recommended videos grab our attention, and we start browsing them and waste our time. It would be nice if we have an option for a blank page so that we can focus on what we want to search rather than on recommendations.
