### ISSUE TITLE
A VR version of the app would be amazing 

### ISSUE THREAD

**Issue by IceFireDude** [Frontesque/VueTube#59]
Like obviously this is the last thing ever to be even considered I'm sure but it would be amazing if you got a VR version of this app for the quest and cause the quest is like a android phone I can see this working almost right out of the box :)

**Comment by Frontesque** [comment]
For quest, Facebook guards that so tightly, we wouldn't be able to afford the developer license.

**Comment by federico2407** [comment]
I think this feature request should be considered again since the recently announced Digital Markets Act, expected to come into force in october, would force Meta to allow third-party apps and stores on the quest, also we can already install third party apps having a developer account, sidequest is full of examples of that
