### ISSUE TITLE
Buttons stay highlighted

### ISSUE THREAD

**Issue by SadSpear** [Frontesque/VueTube#82]
**Describe the bug**
Buttons can stay highlighted if you press long enough on them

**To Reproduce**
1. Go to any page where there are buttons
2. Long press on any button and then let go
3. The button should stay highlighted

**Expected behavior**
The button should not stay highlighted

**Screenshots**
[Screen recording](https://www.youtube.com/watch?v=0oPAxJKujPY)

**Device Information**
 - OS: Android 12
 - App Version ecc29af

**Comment by Minozzzi** [comment]
I would like to try to resolve this issue, could you sign an issue for me?

**Comment by 404-Program-not-found** [comment]
> I would like to try to resolve this issue, could you sign an issue for me?

You can just fix the bug and do a PR.

**Comment by Minozzzi** [comment]
Guys, i found the problem. It's a problem caused by vuetify and solve it by applying this css `
.myClass:focus::before {
   opacity: 0 !important;
}.
` But I don't know much about Vue and the project, it would be interesting to apply this class globally.

See demonstration: https://www.loom.com/share/a62fcdd4a1b24445bb48a30225c49716
